# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: '0/5 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run API
      run: |
        python run.py
      env:
        FT_API_UID: ${{ secrets.FT_API_UID }}
        FT_API_SECRET: ${{ secrets.FT_API_SECRET }}
        GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
        GH_API_USER: ${{ secrets.GH_API_USER }}
        GH_API_REPO: ${{ secrets.GH_API_REPO }}
